// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Expense.Entities.Models;

public partial class Currency
{
    public int IdCur { get; set; }

    public string CurCode { get; set; }

    public string CurName { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}