// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Expense.Entities.Models;

public partial class Expense
{
    public int IdExp { get; set; }

    public int IdNat { get; set; }

    public int IdUsr { get; set; }

    public DateTime? ExpDate { get; set; }

    public decimal? ExpAmount { get; set; }

    public string ExpCommentary { get; set; }

    public virtual Nature Nature { get; set; }

    public virtual User User { get; set; }
}