// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Expense.Entities.Models;

public partial class Nature
{
    public int IdNat { get; set; }

    public string NatCode { get; set; }

    public string NatName { get; set; }

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();
}