// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Expense.Entities.Models;

public partial class User
{
    public int IdUsr { get; set; }

    public int IdCur { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    public virtual Currency Currency { get; set; }
}